{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/ignore_list.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-13T11:34:39.356122Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/languages.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-13T11:34:39.356776Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/parsers.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-13T11:34:39.357326Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/prompts.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-13T11:34:39.358067Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/tool_config.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-13T11:34:39.362384Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Configuration file loaded: /home/adminuser/venv/lib/python3.11/site-packages/readmeai/config/settings/tooling.toml",
"level": "info",
"logger": "readmeai.config.settings",
"timestamp": "2025-09-13T11:34:39.363639Z",
"filename": "settings.py",
"func_name": "_load_settings",
"lineno": 276
}
{
"event": "Pydantic settings: dict_keys(['config', 'ignore_list', 'languages', 'parsers', 'prompts', 'tool_config', 'tooling'])",
"level": "info",
"logger": "readmeai.cli.main",
"timestamp": "2025-09-13T11:34:39.365077Z",
"filename": "main.py",
"func_name": "main",
"lineno": 86
}
{
"event": "Repository settings: repository='https://github.com/Sameer-Agg/RestroDineIn' full_name='Sameer-Agg/RestroDineIn' host_domain='github.com' host='github' name='RestroDineIn'",
"level": "info",
"logger": "readmeai.cli.main",
"timestamp": "2025-09-13T11:34:39.365242Z",
"filename": "main.py",
"func_name": "main",
"lineno": 87
}
{
"event": "LLM API settings: api='GEMINI' base_url='https://api.openai.com/v1/chat/completions' context_window=3900 encoder='cl100k_base' host_name=Url('https://api.openai.com/') localhost=Url('http://localhost:11434/') model='gemini-1.5-pro' path='v1/chat/completions' temperature=0.1 tokens=699 top_p=0.9",
"level": "info",
"logger": "readmeai.cli.main",
"timestamp": "2025-09-13T11:34:39.365386Z",
"filename": "main.py",
"func_name": "main",
"lineno": 88
}
{
"event": "Total files analyzed: 35",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-13T11:34:40.004705Z",
"filename": "__main__.py",
"func_name": "log_repository_context",
"lineno": 102
}
{
"event": "Metadata extracted: {'cicd': {}, 'containers': {}, 'documentation': {}, 'package_managers': {'npm': 'package-lock.json, package.json'}}",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-13T11:34:40.004887Z",
"filename": "__main__.py",
"func_name": "log_repository_context",
"lineno": 103
}
{
"event": "Dependencies: ['npm', 'html', 'package.json', 'package-lock.json', 'javascript', 'css', 'eslint-plugin-react-hooks', '@eslint/js', 'globals', 'react-router-dom', '@vitejs/plugin-react', 'eslint-plugin-react-refresh', 'vite', '@types/react-dom', 'eslint', 'react-dom', '@types/react', '@clerk/clerk-react', 'react']",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-13T11:34:40.005058Z",
"filename": "__main__.py",
"func_name": "log_repository_context",
"lineno": 104
}
{
"event": "Languages: {'json': 2, 'js': 2, 'html': 1, 'css': 14, 'jsx': 16}",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-13T11:34:40.007782Z",
"filename": "__main__.py",
"func_name": "log_repository_context",
"lineno": 105
}
{
"event": "Google Generative AI library is not available. Some features will be disabled.",
"level": "warning",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.008100Z",
"filename": "gemini.py",
"func_name": "__init__",
"lineno": 45
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.008781Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.009143Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.009480Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.009759Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.010054Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.010393Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.010660Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.011103Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.011405Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.011654Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.011901Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.012155Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.012429Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.012676Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.012910Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.013167Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.013446Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.013823Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.014090Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.014371Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.014615Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.014864Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.015119Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.015394Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.015636Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.015875Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.016124Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.016525Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.016785Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.017021Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.017335Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.017580Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.017823Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.018075Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.018347Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.018833Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.019126Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "Cannot make request: Google Generative AI library is not available.",
"level": "error",
"logger": "readmeai.models.base",
"timestamp": "2025-09-13T11:34:40.019595Z",
"filename": "gemini.py",
"func_name": "_make_request",
"lineno": 104
}
{
"event": "README.md file generated successfully.",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-13T11:34:40.031296Z",
"filename": "__main__.py",
"func_name": "log_process_completion",
"lineno": 110
}
{
"event": "Output file saved @ /tmp/tmp_m8oh0lj.md",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-13T11:34:40.031473Z",
"filename": "__main__.py",
"func_name": "log_process_completion",
"lineno": 111
}
{
"event": "Share with us @ github.com/eli64s/readme-ai/discussions",
"level": "info",
"logger": "readmeai.__main__",
"timestamp": "2025-09-13T11:34:40.031633Z",
"filename": "__main__.py",
"func_name": "log_process_completion",
"lineno": 112
}
